name: friendly_fire_peripherals
description: A package for managing Friendly Fire peripherals (gear).
version: 0.2.1

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  ffi: ^2.0.1
  path: ^1.8.1
  faker: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
